// Class: ReadBDT4
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/07       [396295]
Creator        : zzshi
Date           : Fri Jul 12 14:17:16 2019
Host           : Linux vocms0315.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /export/d00/scratch/zzshi/CMSSW_10_3_2/src/JingTMVA/TMVA/BmesonRun2018/tmva/train
Training events: 35036
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "4000" [Number of trees in the forest]
MaxDepth: "4" [Max depth of the decision tree allowed]
MinNodeSize: "3.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "25000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "8.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "8.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "8.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
Btrk1Pt                       Btrk1Pt                       Btrk1Pt                       Btrk1Pt                                                         'F'    [1.00033950806,19.3318405151]
Btrk2Pt                       Btrk2Pt                       Btrk2Pt                       Btrk2Pt                                                         'F'    [1.00004661083,19.8820571899]
abs(Btrk1Dz1/Btrk1DzError1)   Trk1DCAz                      Trk1DCAz                      Trk1DCAz                                                        'F'    [5.33300299139e-05,147.441162109]
abs(Btrk2Dz1/Btrk2DzError1)   Trk2DCAz                      Trk2DCAz                      Trk2DCAz                                                        'F'    [0.000212241167901,123.889228821]
abs(Btrk1Dxy1/Btrk1DxyError1) Trk1DCAxy                     Trk1DCAxy                     Trk1DCAxy                                                       'F'    [2.69673728326e-05,127.917175293]
abs(Btrk2Dxy1/Btrk2DxyError1) Trk2DCAxy                     Trk2DCAxy                     Trk2DCAxy                                                       'F'    [7.92917562649e-05,153.660858154]
abs(Btktkmass-1.019455)       MassDis                       MassDis                       MassDis                                                         'F'    [4.39453131662e-08,0.0149986306205]
BsvpvDistance/BsvpvDisErr     dls                           dls                           dls                                                             'F'    [2.00120663643,510.772369385]
Balpha                        Balpha                        Balpha                        Balpha                                                          'F'    [1.88375488506e-05,3.13608837128]
Bd0                           dls2D                         dls2D                         dls2D                                                           'F'    [0.00195517926477,3.30169057846]
cos(Bdtheta)                  cos_Bdtheta_                  cos(Bdtheta)                  cos(Bdtheta)                                                    'F'    [-1,1]
Bchi2cl                       Bchi2cl                       Bchi2cl                       Bchi2cl                                                         'F'    [0.0500281006098,0.999965727329]
Btrk1Eta                      Btrk1Eta                      Btrk1Eta                      Btrk1Eta                                                        'F'    [-2.39955735207,2.39894676208]
Btrk2Eta                      Btrk2Eta                      Btrk2Eta                      Btrk2Eta                                                        'F'    [-2.39128732681,2.39876866341]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT4 : public IClassifierReader {

 public:

   // constructor
   ReadBDT4( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT4" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Btrk1Pt", "Btrk2Pt", "abs(Btrk1Dz1/Btrk1DzError1)", "abs(Btrk2Dz1/Btrk2DzError1)", "abs(Btrk1Dxy1/Btrk1DxyError1)", "abs(Btrk2Dxy1/Btrk2DxyError1)", "abs(Btktkmass-1.019455)", "BsvpvDistance/BsvpvDisErr", "Balpha", "Bd0", "cos(Bdtheta)", "Bchi2cl", "Btrk1Eta", "Btrk2Eta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT4() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT4::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT4::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(2.39504919408659);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476607,-99) , 
8, 0.0462253, 1, 0, 0.583043,-99) , 
7, 4.80217, 0, 0, 0.934586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.929293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0326403,-99) , 
7, 9.07361, 0, 0, 0.112987,-99) , 
0, 1.87508, 0, 0, 0.487926,-99)    );
  // itree = 1
  fBoostWeights.push_back(2.24746);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00627527, 1, 1, 0.975337,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0398473,-99) , 
9, 0.0631929, 0, 0, 0.137548,-99) , 
1, 2.06167, 0, 0, 0.53252,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.55542);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00536063, 1, 1, 0.89114,-99) , 
NN(
0, 
0, 
-1, 0.00381377, 1, -1, 0.139417,-99) , 
0, 1.77501, 0, 0, 0.489688,-99)    );
  // itree = 3
  fBoostWeights.push_back(1.50229);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 5.44035, 0, 1, 0.988231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493805,-99) , 
3, 0.84659, 0, 0, 0.895781,-99) , 
NN(
0, 
0, 
-1, 7.88319, 0, -1, 0.187317,-99) , 
6, 0.00537832, 1, 0, 0.640874,-99)    );
  // itree = 4
  fBoostWeights.push_back(1.53841);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 1.01337, 0, 1, 0.988337,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.898374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38669,-99) , 
10, 0.99968, 0, 0, 0.672164,-99) , 
5, 0.978845, 0, 0, 0.935996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405175,-99) , 
6, 0.0111292, 1, 0, 0.884982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287123,-99) , 
7, 3.25316, 0, 0, 0.75184,-99)    );
  // itree = 5
  fBoostWeights.push_back(1.44937);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.99848, 0, 1, 0.903522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.749729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.259263,-99) , 
3, 1.51647, 0, 0, 0.534062,-99) , 
6, 0.00734192, 1, 0, 0.80058,-99)    );
  // itree = 6
  fBoostWeights.push_back(1.63424);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.114318, 0, 1, 0.91836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0461059,-99) , 
7, 110.089, 1, 0, 0.722242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.185552,-99) , 
1, 1.42637, 0, 0, 0.524969,-99)    );
  // itree = 7
  fBoostWeights.push_back(1.16105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.08876, 0, 1, 0.974152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415446,-99) , 
1, 2.38262, 0, 0, 0.50888,-99) , 
2, 1.50992, 0, 0, 0.738126,-99)    );
  // itree = 8
  fBoostWeights.push_back(1.59179);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.517835, 0, 1, 0.959276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469907,-99) , 
3, 0.214605, 0, 0, 0.928275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.169093,-99) , 
9, 0.66787, 1, 0, 0.884044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385465,-99) , 
10, 0.99832, 0, 0, 0.809693,-99)    );
  // itree = 9
  fBoostWeights.push_back(1.28621);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.999742, 0, 1, 0.926179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.77468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330386,-99) , 
12, 0.497433, 0, 0, 0.517503,-99) , 
6, 0.00690846, 1, 0, 0.755958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.180585,-99) , 
8, 0.0692818, 1, 0, 0.610153,-99)    );
  // itree = 10
  fBoostWeights.push_back(1.91537);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 1.05762, 0, 1, 0.913446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338643,-99) , 
1, 8.23836, 1, 0, 0.873859,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0536352,-99) , 
5, 1.11411, 1, 0, 0.2181,-99) , 
4, 0.440044, 0, 0, 0.755324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0289251,-99) , 
13, -1.99059, 0, 0, 0.541227,-99)    );
  // itree = 11
  fBoostWeights.push_back(1.82089);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.648714, 1, 1, 0.933762,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.187472,-99) , 
0, 2.67354, 0, 0, 0.335702,-99) , 
5, 0.780645, 0, 0, 0.749037,-99)    );
  // itree = 12
  fBoostWeights.push_back(1.67267);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 1.52641, 0, 1, 0.927248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.193296,-99) , 
7, 110.187, 1, 0, 0.834462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240315,-99) , 
1, 1.33714, 0, 0, 0.690688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0510183,-99) , 
11, 0.118218, 0, 0, 0.561942,-99)    );
  // itree = 13
  fBoostWeights.push_back(1.48451);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.16768, 0, 1, 0.967424,-99) , 
NN(
NN(
0, 
0, 
-1, 0.791118, 0, 1, 0.961271,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.185616,-99) , 
13, -0.116309, 1, 0, 0.425288,-99) , 
11, 0.55082, 0, 0, 0.708794,-99) , 
11, 0.167611, 1, 0, 0.893047,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468631,-99) , 
0, 1.31396, 0, 0, 0.815434,-99)    );
  // itree = 14
  fBoostWeights.push_back(1.4006);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.64732, 0, 1, 0.945585,-99) , 
NN(
NN(
0, 
0, 
-1, 0.999735, 0, 1, 0.793062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.19992,-99) , 
10, 0.9988, 0, 0, 0.479816,-99) , 
5, 1.77227, 0, 0, 0.652828,-99)    );
  // itree = 15
  fBoostWeights.push_back(1.66355);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.69415, 0, 1, 0.949459,-99) , 
NN(
NN(
0, 
0, 
0, 4.35556, 0, 1, 0.99994,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.807674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208545,-99) , 
5, 2.16918, 0, 0, 0.327007,-99) , 
1, 2.66237, 0, 0, 0.44727,-99) , 
11, 0.503129, 0, 0, 0.691922,-99)    );
  // itree = 16
  fBoostWeights.push_back(1.53047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00793547, 1, 1, 0.891141,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.102139,-99) , 
11, 0.747817, 0, 0, 0.361698,-99) , 
11, 0.718264, 1, 0, 0.819152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0682514,-99) , 
4, 0.216434, 0, 0, 0.751045,-99)    );
  // itree = 17
  fBoostWeights.push_back(1.70409);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.976217,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.89299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.272855,-99) , 
5, 1.53048, 0, 0, 0.581586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0918857,-99) , 
12, 0.414942, 1, 0, 0.415478,-99) , 
13, 0.657557, 0, 0, 0.559503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6944,-99) , 
NN(
0, 
0, 
-1, 0.00538447, 0, -1, 0.05928,-99) , 
6, 0.00245784, 1, 0, 0.15598,-99) , 
4, 0.885424, 0, 0, 0.302567,-99)    );
  // itree = 18
  fBoostWeights.push_back(1.94581);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.08388, 1, 1, 0.938463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439139,-99) , 
0, 1.34388, 0, 0, 0.803692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0227458,-99) , 
8, 0.0741819, 1, 0, 0.344651,-99)    );
  // itree = 19
  fBoostWeights.push_back(1.30444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.970259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382031,-99) , 
2, 0.790442, 0, 0, 0.746492,-99)    );
  // itree = 20
  fBoostWeights.push_back(2.86904);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999495,-99) , 
NN(
NN(
0, 
0, 
-1, 0.551257, 0, 1, 0.997199,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0864825,-99) , 
12, 0.450175, 1, 0, 0.336964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0778211,-99) , 
6, 0.00499308, 1, 0, 0.17281,-99) , 
0, 2.0487, 0, 0, 0.410763,-99) , 
2, 0.194804, 1, 0, 0.834207,-99)    );
  // itree = 21
  fBoostWeights.push_back(2.26296);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00579745, 1, 1, 0.963756,-99) , 
NN(
0, 
0, 
-1, -1.93968, 0, -1, 0.217434,-99) , 
9, 0.0573837, 1, 0, 0.883235,-99)    );
  // itree = 22
  fBoostWeights.push_back(2.24365);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.277232, 1, 1, 0.942922,-99)    );
  // itree = 23
  fBoostWeights.push_back(2.01659);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.11466, 1, 1, 0.934269,-99) , 
NN(
0, 
0, 
-1, 0.793801, 1, -1, 0.0927832,-99) , 
3, 0.834635, 0, 0, 0.664072,-99)    );
  // itree = 24
  fBoostWeights.push_back(5.31319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0.23112, 0, -1, 0.0839136,-99) , 
1, 2.78563, 0, 0, 0.985771,-99)    );
  // itree = 25
  fBoostWeights.push_back(3.56101);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999123,-99) , 
NN(
0, 
0, 
-1, -0.594363, 1, -1, 0.0120038,-99) , 
7, 5.72595, 0, 0, 0.0541019,-99)    );
  // itree = 26
  fBoostWeights.push_back(2.58951);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.869775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00141945,-99) , 
6, 0.0107422, 1, 0, 0.246687,-99)    );
  // itree = 27
  fBoostWeights.push_back(2.68781);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.930205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00684456,-99) , 
0, 1.53085, 0, 0, 0.398956,-99)    );
  // itree = 28
  fBoostWeights.push_back(1.88136);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0869312,-99)    );
  // itree = 29
  fBoostWeights.push_back(3.48159);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.67699, 0, 1, 0.994814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278825,-99) , 
4, 0.307016, 0, 0, 0.975108,-99)    );
  // itree = 30
  fBoostWeights.push_back(4.97292);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.664051, 0, 1, 0.999176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0399084,-99) , 
4, 0.729623, 1, 0, 0.236301,-99) , 
4, 0.937142, 0, 0, 0.993961,-99)    );
  // itree = 31
  fBoostWeights.push_back(4.93706);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1.36948, 1, 1, 0.997916,-99)    );
  // itree = 32
  fBoostWeights.push_back(2.62677);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.99992, 0, 1, 0.963857,-99)    );
  // itree = 33
  fBoostWeights.push_back(3.08503);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.019956, 1, 1, 0.999072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346456,-99) , 
3, 0.624745, 0, 0, 0.982523,-99) , 
NN(
0, 
0, 
-1, 0.00286097, 1, -1, 0.0313615,-99) , 
10, 0.9992, 0, 0, 0.498924,-99)    );
  // itree = 34
  fBoostWeights.push_back(2.07063);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.56038, 0, 1, 0.9785,-99) , 
NN(
0, 
0, 
-1, 2.20687, 0, -1, 0.0972152,-99) , 
12, -0.556971, 1, 0, 0.415198,-99)    );
  // itree = 35
  fBoostWeights.push_back(2.88798);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.00483008, 1, 1, 0.987244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.931869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.120587,-99) , 
2, 0.611008, 0, 0, 0.426386,-99) , 
7, 4.85021, 0, 0, 0.887677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0186293,-99) , 
3, 0.178605, 0, 0, 0.705235,-99)    );
  // itree = 36
  fBoostWeights.push_back(4.69918);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.97315, 1, 1, 0.990358,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575499,-99) , 
NN(
0, 
0, 
-1, 2.17898, 0, -1, 0.000632347,-99) , 
6, 0.00261442, 1, 0, 0.00323773,-99) , 
0, 2.47539, 0, 0, 0.0381059,-99)    );
  // itree = 37
  fBoostWeights.push_back(3.93861);
  fForest.push_back( 
NN(
0, 
0, 
-1, 5.90814, 0, 1, 0.992777,-99)    );
  // itree = 38
  fBoostWeights.push_back(2.38491);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 0.951715,-99)    );
  // itree = 39
  fBoostWeights.push_back(4.13492);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.739243,-99) , 
NN(
0, 
0, 
-1, -0.0350688, 0, -1, 0.00254325,-99) , 
8, 0.0476026, 1, 0, 0.0114357,-99)    );
  // itree = 40
  fBoostWeights.push_back(1.84359);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1.41242, 0, -1, 0.0907516,-99)    );
  // itree = 41
  fBoostWeights.push_back(3.62721);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.47107, 0, 1, 0.993097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0673195,-99) , 
7, 2.87626, 0, 0, 0.936081,-99)    );
  // itree = 42
  fBoostWeights.push_back(4.15453);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.48854, 0, 1, 0.999841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.115025,-99) , 
7, 2.79554, 0, 0, 0.958516,-99)    );
  // itree = 43
  fBoostWeights.push_back(7.7201);
  fForest.push_back( 
NN(
0, 
0, 
-1, 2.06193, 0, 1, 0.999936,-99)    );
  // itree = 44
  fBoostWeights.push_back(3.62103);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1.89323, 0, 1, 0.989295,-99)    );
  // itree = 45
  fBoostWeights.push_back(4.74357);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0154064, 1, 1, 0.999801,-99) , 
NN(
0, 
0, 
-1, 0.00307607, 0, -1, 0.0031669,-99) , 
0, 1.89132, 0, 0, 0.175805,-99)    );
  // itree = 46
  fBoostWeights.push_back(1.96882);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00415201, 1, 1, 0.921364,-99)    );
  // itree = 47
  fBoostWeights.push_back(5.9551);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.91326, 0, 1, 0.999618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.000609402,-99) , 
0, 1.53633, 0, 0, 0.109409,-99)    );
  // itree = 48
  fBoostWeights.push_back(6.38727);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00205427, 1, 1, 0.999819,-99) , 
NN(
0, 
0, 
-1, 1.12458, 1, -1, 0.000769286,-99) , 
8, 0.0371484, 1, 0, 0.728729,-99)    );
  // itree = 49
  fBoostWeights.push_back(1.25168);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 0.827013,-99)    );
  // itree = 50
  fBoostWeights.push_back(4.80852);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1.77114, 0, -1, 0.00244648,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.240744);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 0.57467,-99)    );
  // itree = 52
  fBoostWeights.push_back(6.8602);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 7.48492, 0, 1, 0.999988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177133,-99) , 
5, 0.393619, 0, 0, 0.997057,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 2.45985e-05,-99) , 
1, 2.38248, 0, 0, 0.00128637,-99) , 
7, 5.90841, 0, 0, 0.265643,-99)    );
  // itree = 53
  fBoostWeights.push_back(8.91743);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 3.30376, 0, 1, 0.999998,-99) , 
NN(
0, 
0, 
-1, 0.76533, 1, -1, 1.48502e-05,-99) , 
1, 2.1601, 0, 0, 0.0328722,-99)    );
  // itree = 54
  fBoostWeights.push_back(5.38869);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 5.57776, 0, 1, 0.999999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00175215,-99) , 
0, 1.7651, 0, 0, 0.324456,-99)    );
  // itree = 55
  fBoostWeights.push_back(13.3591);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 4.37038e-08,-99) , 
1, 1.89728, 0, 0, 0.00180977,-99)    );
  // itree = 56
  fBoostWeights.push_back(1.6562);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 0.112023,-99)    );
  // itree = 57
  fBoostWeights.push_back(9.46683);
  fForest.push_back( 
NN(
0, 
0, 
-1, -2.00235, 0, 1, 0.999993,-99)    );
  // itree = 58
  fBoostWeights.push_back(14.9503);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.31165, 0, 1, 1,-99)    );
  // itree = 59
  fBoostWeights.push_back(11.1433);
  fForest.push_back( 
NN(
0, 
0, 
-1, 1.53497, 0, 1, 0.999999,-99)    );
  // itree = 60
  fBoostWeights.push_back(21.2624);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.36329, 0, 1, 1,-99)    );
  // itree = 61
  fBoostWeights.push_back(14.0492);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.68224, 0, 1, 1,-99)    );
  // itree = 62
  fBoostWeights.push_back(22.5464);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.31636, 1, 1, 1,-99)    );
  // itree = 63
  fBoostWeights.push_back(21.7949);
  fForest.push_back( 
NN(
0, 
0, 
1, 6.68071, 0, 1, 1,-99)    );
  // itree = 64
  fBoostWeights.push_back(26.9673);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99)    );
  // itree = 65
  fBoostWeights.push_back(24.1801);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99)    );
  // itree = 66
  fBoostWeights.push_back(14.8417);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99)    );
  // itree = 67
  fBoostWeights.push_back(17.9756);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99)    );
  // itree = 68
  fBoostWeights.push_back(29.2166);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99)    );
  // itree = 69
  fBoostWeights.push_back(25.7911);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99)    );
  // itree = 70
  fBoostWeights.push_back(5.90203);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 0.999375,-99)    );
  // itree = 71
  fBoostWeights.push_back(27.1662);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 1.78777e-15,-99)    );
  // itree = 72
  fBoostWeights.push_back(63.5407);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 3.20478e-35,-99)    );
  // itree = 73
  fBoostWeights.push_back(2.9443);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 0.975407,-99)    );
  // itree = 74
  fBoostWeights.push_back(16.0671);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.32443, 0, -1, 1.89544e-09,-99)    );
  // itree = 75
  fBoostWeights.push_back(65.5599);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.3131, 0, -1, 2.5682e-36,-99)    );
  // itree = 76
  fBoostWeights.push_back(71.6493);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.29708, 1, -1, 0,-99)    );
  // itree = 77
  fBoostWeights.push_back(72.3883);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.30875, 1, -1, 0,-99)    );
  // itree = 78
  fBoostWeights.push_back(52.9548);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 1.78858e-29,-99)    );
  // itree = 79
  fBoostWeights.push_back(9.84385);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 0.999995,-99)    );
  // itree = 80
  fBoostWeights.push_back(61.0644);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 7.08063e-34,-99)    );
  // itree = 81
  fBoostWeights.push_back(68.6812);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 5.18969e-38,-99)    );
  // itree = 82
  fBoostWeights.push_back(47.5833);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 1.47419e-26,-99)    );
  // itree = 83
  fBoostWeights.push_back(6.42145);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, 1, 0.999673,-99)    );
  // itree = 84
  fBoostWeights.push_back(57.1026);
  fForest.push_back( 
NN(
0, 
0, 
0, 1.30128, 0, -1, 1.00195e-31,-99)    );
  // itree = 85
  fBoostWeights.push_back(58.9873);
  fForest.push_back( 
NN(
0, 
0, 
1, 1.38296, 0, -1, 9.49894e-33,-99)    );
  // itree = 86
  fBoostWeights.push_back(77.0648);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99)    );
  // itree = 87
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0, 1, -1, 0.5,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT4::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT4::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
